### ISSUE TITLE
Error when load dataset

### ISSUE THREAD

**Issue by yunjian-hash** [lab-cosmo/chemiscope#234]
Dear developers,

when I use the load/save function with my Al_chemiscope.json.gz file, there is an error. what's the problem and how can I resolve it. Thanks! 

RangeError: Invalid string length

Backtrace
RangeError: Invalid string length
at Array.join (<anonymous>)
at b.onEnd (https://chemiscope.org/chemiscope-app.min.js:2:1388015)
at b.push (https://chemiscope.org/chemiscope-app.min.js:2:1387813)
at y (https://chemiscope.org/chemiscope-app.min.js:2:1386744)
at d (https://chemiscope.org/chemiscope-app.min.js:2:2859495)
at https://chemiscope.org/chemiscope-app.min.js:2:2857878
at FileReader.r.onload (https://chemiscope.org/chemiscope-app.min.js:2:2859710)

**Comment by ceriottm** [comment]
dear yunjian, it'd be hard to help you without knowing how Al_chemiscope.json.gz has been created. Perahps you can give some more details, and attach here the actual file.

**Comment by ceriottm** [comment]
It'd be great if you could link the actual files - it's kind of tricky to debug without being able to trigger the error.

**Comment by yunjian-hash** [comment]
> It'd be great if you could link the actual files - it's kind of tricky to debug without being able to trigger the error.

Dear ceriottm,

The actual files are too large. Thus, please kindly find the shared link below to download. Thanks so much for your kind help!
https://we.tl/t-uGaMagbF01

**Comment by Luthaf** [comment]
Ok, so it looks like the dataset is too big for a browser environment, and we are overflowing allowed allocations when constructing the in-memory representation of the dataset.

There is not much we can do here, apart from trying to give a better error message. (lazily loaded structures might help as well, but this requires writing some JS code & making the files available somewhere online)

----

@yunjian-hash, a simple fix for now would be to only take every tenth frame, with something like this 

```py
#!/usr/bin/env python
# coding: utf-8

import ase
import ase.io
import numpy as np
from chemiscope import write_input

frames = ase.io.read("trj.xyz", "::10")

fileName = "COLVAR"


def readlines(fileName):
    with open(fileName, "r") as f:
        lines = f.readlines()[1:]  # 从第二行是1，
        print("total lines:", len(lines))
        lines = list(map(lambda x: x.strip(), lines))
    for j in range(len(lines)):
        lines[j] = list(map(lambda x: float(x), lines[j].split()))
    return lines


cv1List = []
cv2List = []
for time, cv1, cv2 in readlines(fileName):
    x = cv1
    y = cv2
    cv1List.append(x)
    cv2List.append(y)

properties = {
    "CN(Ca_Os)": {
        "target": "structure",
        "values": cv1List[::10],
        "description": "CN(Ca_Os)",
    },
    " CN(Ca_Ow)": {
        "target": "structure",
        "values": cv2List[::10],
        "description": "CN(Ca_Ow)",
    },
}
write_input("Al_chemiscope-small.json.gz", frames=frames, properties=properties)
```

**Comment by yunjian-hash** [comment]
> Ok, so it looks like the dataset is too big for a browser environment, and we are overflowing allowed allocations when constructing the in-memory representation of the dataset.
> 
> There is not much we can do here, apart from trying to give a better error message. (lazily loaded structures might help as well, but this requires writing some JS code & making the files available somewhere online)
> 
> @yunjian-hash, a simple fix for now would be to only take every tenth frame, with something like this
> 
> ```python
> #!/usr/bin/env python
> # coding: utf-8
> 
> import ase
> import ase.io
> import numpy as np
> from chemiscope import write_input
> 
> frames = ase.io.read("trj.xyz", "::10")
> 
> fileName = "COLVAR"
> 
> 
> def readlines(fileName):
>     with open(fileName, "r") as f:
>         lines = f.readlines()[1:]  # 从第二行是1，
>         print("total lines:", len(lines))
>         lines = list(map(lambda x: x.strip(), lines))
>     for j in range(len(lines)):
>         lines[j] = list(map(lambda x: float(x), lines[j].split()))
>     return lines
> 
> 
> cv1List = []
> cv2List = []
> for time, cv1, cv2 in readlines(fileName):
>     x = cv1
>     y = cv2
>     cv1List.append(x)
>     cv2List.append(y)
> 
> properties = {
>     "CN(Ca_Os)": {
>         "target": "structure",
>         "values": cv1List[::10],
>         "description": "CN(Ca_Os)",
>     },
>     " CN(Ca_Ow)": {
>         "target": "structure",
>         "values": cv2List[::10],
>         "description": "CN(Ca_Ow)",
>     },
> }
> write_input("Al_chemiscope-small.json.gz", frames=frames, properties=properties)
> ```

Thanks for your help! The problem has been solved.
